name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v2  
      - name: script
        run: ci/build-app.sh
      - name: second-script
        run: ci/unit-test-app.sh