name: JAVA CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v2
      - name: first   
        run: chmod +x ci/build-app.sh && ci/build-app.sh

  Build:
    runs-on: ubuntu:latest
    needs: [Clone-Down]
    container: gradle:6-jdk11
    steps:
      - name: build-step
        uses: actions/upload-artifact@v2
      - name: test run  
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      